---
title: "Customer Churn Prediction"
author: "Shruty"
date: "2022-12-10"
output: html_document
---

```{r}
#importing libraries

library(plyr)  
library(rpart.plot) 
library(caret)
library(gridExtra) 
library(tidyverse) 
library(rsample)
library(e1071) 
library(GGally)
library(data.table)
library(DT)
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(corrplot)
library(rms)
library(MASS)
library(e1071)
library(ROCR)
library(gplots)
library(gtools)
library(pROC)
library(rpart)
library(randomForest)
library(ggpubr)

```

```{r}
#loading dataset

churn <- read_csv("churn_dataset.csv")
str(churn)

```

```{r}
#Data Preprocessing

#missing values
sum(is.na(churn))
sapply(churn, function(x) sum(is.na(x)))

sum(is.na(churn$TotalCharges))/nrow(churn)
#churn_clean <- churn[complete.cases(churn), ]

#omit missing values
churn <- na.omit(churn)
churn_clean <- churn[complete.cases(churn), ]
```

```{r}

#Data Transformation

#Senior citizen should not be o and 1, so converting it to yes or no
churn_clean$SeniorCitizen <- as.factor(mapvalues(churn_clean$SeniorCitizen,
                                                 from=c("0", "1"),
                                                 to=c("No", "Yes")))


churn_clean$MultipleLines <- as.factor(mapvalues(churn_clean$MultipleLines, 
                                                 from=c("No phone service"),
                                                 to=c("No")))

churn_clean$OnlineSecurity <- as.factor(mapvalues(churn_clean$OnlineSecurity, 
                                                 from=c("No internet service"),
                                                 to=c("No")))

churn_clean$OnlineBackup <- as.factor(mapvalues(churn_clean$OnlineBackup, 
                                                  from=c("No internet service"),
                                                  to=c("No")))

churn_clean$DeviceProtection <- as.factor(mapvalues(churn_clean$DeviceProtection, 
                                                  from=c("No internet service"),
                                                  to=c("No")))

churn_clean$TechSupport <- as.factor(mapvalues(churn_clean$TechSupport, 
                                                  from=c("No internet service"),
                                                  to=c("No")))

churn_clean$StreamingTV <- as.factor(mapvalues(churn_clean$StreamingTV, 
                                                  from=c("No internet service"),
                                                  to=c("No")))

churn_clean$StreamingMovies <- as.factor(mapvalues(churn_clean$StreamingMovies, 
                                                  from=c("No internet service"),
                                                  to=c("No")))

churn_clean$customerID <- NULL
```

```{r}
#correlation test: Hypothesis testing:

#chi square test between churn and gender (between categorical column)

rel <- table(churn_clean$Churn, churn_clean$gender)
rel

chisq.test(rel, correct=FALSE)$expected

chisq.test(rel, correct=FALSE)
###as p value is > 0.05 we donot reject the null hypothesis which means there in no
#associaltion between gender and churn

```
```{r}
##########Correlation test betwenn numerical data
cor(churn_clean$tenure, churn_clean$MonthlyCharges)
cor.test(churn_clean$tenure, churn_clean$MonthlyCharges)


cor(churn_clean$tenure, churn_clean$TotalCharges)
cor.test(churn_clean$tenure, churn_clean$TotalCharges)


cor(churn_clean$TotalCharges, churn_clean$MonthlyCharges)
cor.test(churn_clean$MonthlyCharges, churn_clean$MonthlyCharges)
#strong correlation between total and monthly charges
```

```{r}
#####Using ANOVA to see if categorical group has an impact on numerical variable
#contract has an impact on MonthlyCharge

aggregate(MonthlyCharges~Contract, churn_clean, mean)
aggregate(MonthlyCharges~Contract, churn_clean, sd)

#Since the largest standard deviation is not more than twice the smallest standard deviation 
#we can conclude that the assumptions are satisfied, and we can go ahead with the test. 

anova_1 = aov(churn_clean$MonthlyCharges~churn_clean$Contract)
summary(anova_1)

#since p-val < 0.05 we reject the null hypothesis.
#There is a high impact on the  Monthlycharge based on the contract

```

```{r}
#Data Visualization for Descriptive Statistics

#Demographic Visualization

#Gender plot
p1 <- ggplot(churn_clean, aes(x = gender)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3) 

#Senior citizen plot
p2 <- ggplot(churn_clean, aes(x = SeniorCitizen)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Partner plot
p3 <- ggplot(churn_clean, aes(x = Partner)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Dependents plot
p4 <- ggplot(churn_clean, aes(x = Dependents)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)
  
plot(p4)
#Plot demographic data within a grid
grid.arrange(p1, p2, p3, p4, ncol=2)

####Offered Services

#Phone service plot
p5 <- ggplot(churn_clean, aes(x = PhoneService)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Multiple phone lines plot
p6 <- ggplot(churn_clean, aes(x = MultipleLines)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Internet service plot
p7 <- ggplot(churn_clean, aes(x = InternetService)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Online security service plot
p8 <- ggplot(churn_clean, aes(x = OnlineSecurity)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Online backup service plot
p9 <- ggplot(churn_clean, aes(x = OnlineBackup), col = "yellow") +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Device Protection service plot
p10 <- ggplot(churn_clean, aes(x = DeviceProtection)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Tech Support service plot
p11 <- ggplot(churn_clean, aes(x = TechSupport)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Streaming TV service plot
p12 <- ggplot(churn_clean, aes(x = StreamingTV)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Streaming Movies service plot
p13 <- ggplot(churn_clean, aes(x = StreamingMovies)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Plot service data within a grid
grid.arrange(p5, p6, p7,
             p8, p9, p10,
             p11, p12, p13,
             ncol=3)



#####Other categorical Variable

#Contract status plot
p14 <- ggplot(churn_clean, aes(x = Contract)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Paperless billing plot
p15 <- ggplot(churn_clean, aes(x = PaperlessBilling)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Payment method plot
p16 <- ggplot(churn_clean, aes(x = PaymentMethod)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Plot contract data within a grid
grid.arrange(p14, p15, p16, ncol=1)



########Quantitative variables

#Tenure histogram
p17 <- ggplot(data = churn_clean, aes(tenure, color = Churn))+
  geom_freqpoly(binwidth = 5, size = 1)

#Monthly charges histogram
p18 <- ggplot(data = churn_clean, aes(MonthlyCharges, color = Churn))+
  geom_freqpoly(binwidth = 5, size = 1)

#Total charges histogram
p19 <- ggplot(data = churn_clean, aes(TotalCharges, color = Churn))+
  geom_freqpoly(binwidth = 200, size = 1)

#Plot quantitative data within a grid
grid.arrange(p17, p18, p19, ncol=1)


######Visualizing churn variable

p20 <- ggplot(churn_clean, aes(x = Churn)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.., 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)
p20


```


```{r}
#Checking for Correlation
churn_clean %>%
  dplyr::select (TotalCharges, MonthlyCharges, tenure) %>%
  cor() %>%
  corrplot.mixed(upper = "circle", tl.col = "black", number.cex = 0.7)

#scatter plot

plot(churn_clean$MonthlyCharges, churn_clean$TotalCharges, main = "MonthlyCharges vs TotalCharges",
     xlab = "MonthlyCharges", ylab = "TotalCharges",
     pch = 19, frame = FALSE, col = "orange")


#Density plot for Total, Monthly charges and tenure

# Change density plot fill colors by groups for TotalCharges
ggplot(churn_clean, aes(x=TotalCharges, fill=Churn)) +
  geom_density()
# Use semi-transparent fill
p21<-ggplot(churn_clean, aes(x=TotalCharges, fill=Churn)) +
  geom_density(alpha=0.4)
p21

#for Monthly charges
ggplot(churn_clean, aes(x=MonthlyCharges, fill=Churn)) +
  geom_density()
#or
p22<-ggplot(churn_clean, aes(x=MonthlyCharges, fill=Churn)) +
  geom_density(alpha=0.4)
p22

#for tenure
ggplot(churn_clean, aes(x=tenure, fill=Churn)) +
  geom_density()
#or
p23<-ggplot(churn_clean, aes(x=tenure, fill=Churn)) +
  geom_density(alpha=0.4)
p23

grid.arrange(p21, p22, p23, ncol=1)

#boxplot and violine plot

#monthlycharges vs churn
p24 <- ggplot(churn_clean, aes(Churn, MonthlyCharges, fill = Churn))
p24 + geom_violin(alpha = 0.4) + geom_boxplot(width = .2, alpha = 0.4)


#box_plot
ggplot(data =churn_clean, aes(x=Churn, y=MonthlyCharges)) + 
  geom_boxplot(aes(fill=Churn)) 

#totalcharges vs churn
p25 <- ggplot(churn_clean, aes(Churn, TotalCharges, fill = Churn))
p25 + geom_violin(alpha = 0.4) + geom_boxplot(width = .2, alpha = 0.4)


#tenure vs churn
p26 <- ggplot(churn_clean, aes(Churn, tenure, fill = Churn))
p26 + geom_violin(alpha = 0.4) + geom_boxplot(width = .2, alpha = 0.4)


```

```{r}
#changing response variable to numerical
churn_clean$Churn <- as.factor(mapvalues(churn_clean$Churn,
                                         from=c("Yes", "No"),
                                         to=c(1,0)))

churn_clean$SeniorCitizen <- as.factor(mapvalues(churn_clean$SeniorCitizen,
                                                 from=c("No","Yes"),
                                                 to=c(0, 1)))

churn_clean$Partner <- as.factor(mapvalues(churn_clean$Partner,
                                                 from=c("No","Yes"),
                                                 to=c(0, 1)))

churn_clean$Dependents <- as.factor(mapvalues(churn_clean$Dependents,
                                                 from=c("No","Yes"),
                                                 to=c(0, 1)))

churn_clean$PhoneService <- as.factor(mapvalues(churn_clean$PhoneService,
                                                 from=c("No","Yes"),
                                                 to=c(0, 1)))


churn_clean$MultipleLines <- as.factor(mapvalues(churn_clean$MultipleLines, 
                                                 from=c("No", "Yes"),
                                                 to=c(0, 1)))

churn_clean$OnlineSecurity <- as.factor(mapvalues(churn_clean$OnlineSecurity, 
                                                  from=c("No", "Yes"),
                                                  to=c(0, 1)))

churn_clean$OnlineBackup <- as.factor(mapvalues(churn_clean$OnlineBackup, 
                                                from=c("No", "Yes"),
                                                to=c(0, 1)))

churn_clean$DeviceProtection <- as.factor(mapvalues(churn_clean$DeviceProtection, 
                                                    from=c("No", "Yes"),
                                                    to=c(0, 1)))

churn_clean$TechSupport <- as.factor(mapvalues(churn_clean$TechSupport, 
                                               from=c("No", "Yes"),
                                               to=c(0, 1)))

churn_clean$StreamingTV <- as.factor(mapvalues(churn_clean$StreamingTV, 
                                               from=c("No", "Yes"),
                                               to=c(0, 1)))

churn_clean$StreamingMovies <- as.factor(mapvalues(churn_clean$StreamingMovies, 
                                                   from=c("No", "Yes"),
                                                   to=c(0, 1)))

churn_clean$PaperlessBilling <- as.factor(mapvalues(churn_clean$PaperlessBilling, 
                                                   from=c("No", "Yes"),
                                                   to=c(0, 1)))

churn_clean$InternetService <- as.factor(mapvalues(churn_clean$InternetService, 
                                                    from=c("No", "DSL", "Fiber optic"),
                                                    to=c(0, 1, 2)))

churn_clean$gender <- as.factor(mapvalues(churn_clean$gender, 
                                                   from=c("Male", "Female"),
                                                   to=c(0, 1)))

churn_clean$Contract <- as.factor(mapvalues(churn_clean$Contract, 
                                                   from=c("Month-to-month", "One year", "Two year"),
                                                   to=c(0, 1, 2)))

churn_clean$PaymentMethod <- as.factor(mapvalues(churn_clean$PaymentMethod, 
                                                   from=c("Bank transfer (automatic)", "Credit card (automatic)", "Electronic check", "Mailed check"),
                                                   to=c(0, 1, 2, 3)))

churn_clean_num <- churn_clean

```


```{r}
#Splitting data into train and test
intrain <- createDataPartition(churn_clean$Churn, p = 0.8, list = FALSE)
set.seed(2018)
training <- churn_clean[intrain, ]
testing <- churn_clean[- intrain, ]

# Remove Total Charges from the training dataset

churn_train <- training[,-19]
churn_test <- testing[,-19]


dim(churn_train); dim(churn_test)
```

```{r}
#logistic Regression

LogModel <- glm(Churn ~ ., family = binomial(link = "logit"), data = churn_train)
print(summary(LogModel))

anova(LogModel, test = "Chisq")
```

```{r}
churn_test$Churn <- as.character(churn_test$Churn)
churn_test$Churn[churn_test$Churn == "No"] <- "0"
churn_test$Churn[churn_test$Churn == "Yes"] <- "1"
fitted_results <- predict(LogModel, newdata = churn_test, type = "response")
fitted_results <- ifelse(fitted_results > 0.5, 1, 0)

#misclassification error
misClasificError <- mean(fitted_results != churn_test$Churn)
misClasificError

#accuracy
print(paste('Logistic Regression Accuracy', 1- misClasificError))

#confusion matrix
print("Confusion Matrix for Logistic Regression")
table(churn_test$Churn, fitted_results > 0.5)
```

```{r}
##Decision Tree

library(MASS)
library(randomForest)
library(tree)
library(caret)
library(tidyverse) 
library(dplyr)
library(ISLR)


churn_tree <- tree(Churn ~ Contract+tenure+PaperlessBilling, training)
plot(churn_tree)
summary(churn_tree)


library(rpart)
library(rattle)

churn_tree2 = rpart(Churn ~., churn_train)

fancyRpartPlot(churn_tree2)## you need 'rattle' to use this

library(sparkline)
library(visNetwork)# to make this viz, you need to use the package "rpart"
visTree(churn_tree2)


```
```{r}
#confusion matrix of tree
pred_tree <- predict(churn_tree, churn_test)
print("Confusion Matrix for Decision Tree"); table(Predicted = pred_tree, Actual = churn_test$Churn)


p1 <- predict(tree, churn_train)
tab1 <- table(Predicted = p1, Actual = churn_train$Churn)
tab2 <- table(Predicted = pred_tree, Actual = churn_train$Churn)

misClasificError <- (1 - sum(diag(tab2))/sum(tab2))
misClasificError

print(paste('Decision Tree Accuracy',sum(diag(tab2))/sum(tab2)))

```



```{r}
##Random Forest

rfModel <- randomForest(Churn ~., data = churn_train)
print(rfModel)

pred_rf <- predict(rfModel, churn_test)
#caret::confusionMatrix(pred_rf, testing$Churn)
table(Predicted = pred_rf, Actual = churn_test$Churn)

plot(rfModel)
```

```{r}
#Tune the Random Forest

t <- tuneRF(churn_train[, -19], churn_train[, 19], stepFactor = 0.5, plot = TRUE,
            ntreeTry = 200, trace = TRUE, improve = 0.05)


#Fit random model after tuning
rfModel_new <- randomForest(Churn ~., data = churn_train, ntree = 200,
                            mtry = 2, importance = TRUE, proximity = TRUE)
print(rfModel_new)


#Random Forest Predictions and Confusion Matrix After Tuning
pred_rf_new <- predict(rfModel_new, churn_test)
#caret::confusionMatrix(pred_rf_new, testing$Churn)
table(Predicted = pred_rf_new, Actual = churn_test$Churn)


varImpPlot(rfModel_new, sort=T, n.var = 10, main = 'Top 10 Feature Importance')
```